### ISSUE TITLE
Monitoring postfix in docker container

### ISSUE THREAD

**Issue by xpliz** [Hsn723/postfix_exporter#109]
As far I understand commands --docker.enable=true should enable docker and --docker.container.id=postfix-blah should specify which postfix container to listen to, but it throws me an error in latest docker image.

```bash
❯ docker run --rm ghcr.io/hsn723/postfix_exporter --docker.host=true

postfix_exporter: error: unknown long flag '--docker.host', try --help
```
```bash
❯ docker run --rm ghcr.io/hsn723/postfix_exporter --help
usage: postfix_exporter [<flags>]

Prometheus metrics exporter for postfix

Flags:
  --help                        Show context-sensitive help (also try
                                --help-long and --help-man).
  --web.listen-address=":9154"  Address to listen on for web interface and
                                telemetry.
  --web.telemetry-path="/metrics"
                                Path under which to expose metrics.
  --postfix.showq_path="/var/spool/postfix/public/showq"
                                Path at which Postfix places its showq socket.
  --log.unsupported             Log all unsupported lines.
  --postfix.logfile_path="/var/log/mail.log"
                                Path where Postfix writes log entries.
  --postfix.logfile_must_exist  Fail if the log file doesn't exist.
  --postfix.logfile_debug       Enable debug logging for the log file.
```

It seems there are no options for docker flags?

**Comment by Hsn723** [comment]
The docker image is built with the `nodocker,nosystemd` build tags, so those flags are not available. When running `postfix` in a container, you can either build and run `postfix_exporter` locally, omitting the above build tags to include docker support. If you want to run both `postfix` and `postfix_exporter` in a docker environment (like docker compose) or kubernetes environment, you should get `postfix` to write logs in a commonly accessible location so that `postfix_exporter` can tail the logs.
